export function DisclaimerBanner({ prominent = false }: { prominent?: boolean }) {
  return (
    <div
      className={
        prominent
          ? "border-2 border-red-600 bg-red-50 text-red-900 rounded-md p-4 text-sm font-medium"
          : "border border-amber-400 bg-amber-50 text-amber-900 rounded-md p-3 text-sm"
      }
    >
      <strong>AI-assisted draft — not a diagnosis.</strong> This interpretation was
      generated by an AI model and has not been verified by a physician until
      explicitly signed off below. Do not treat it as a final clinical
      conclusion; review, edit, and confirm every finding before relying on it.
    </div>
  );
}
