export function DisclaimerBanner({
  prominent = false,
  moduleType,
}: {
  prominent?: boolean;
  moduleType?: "lab" | "ecg" | "imaging" | "prescription";
}) {
  const isImaging = moduleType === "imaging";

  return (
    <div
      className={
        isImaging
          ? "border-4 border-red-700 bg-red-100 text-red-950 rounded-md p-4 text-sm font-semibold"
          : prominent
            ? "border-2 border-red-600 bg-red-50 text-red-900 rounded-md p-4 text-sm font-medium"
            : "border border-amber-400 bg-amber-50 text-amber-900 rounded-md p-3 text-sm"
      }
    >
      <strong>AI-assisted draft — not a diagnosis.</strong> This interpretation was
      generated by an AI model and has not been verified by a physician until
      explicitly signed off below. Do not treat it as a final clinical
      conclusion; review, edit, and confirm every finding before relying on it.
      {isImaging && (
        <>
          {" "}
          <strong>
            Imaging findings below are unverified observations only, not a
            radiological diagnosis
          </strong>{" "}
          — this is the highest-liability module in this tool. Every item
          must be independently verified against the actual image before any
          clinical decision is made.
        </>
      )}
    </div>
  );
}
